// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoImw5zUJ8KakACW_apfOEx69jjTHdU4E',
    appId: '1:278933192533:web:5cf382c5355afb8fc5f9dc',
    messagingSenderId: '278933192533',
    projectId: 'kopichat-a8dc3',
    authDomain: 'kopichat-a8dc3.firebaseapp.com',
    storageBucket: 'kopichat-a8dc3.appspot.com',
    measurementId: 'G-1TH0DCVTVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxEHkHfJwvgQ1H9YNSSmGC22-ltMn21fA',
    appId: '1:278933192533:android:e8587e795a9ea543c5f9dc',
    messagingSenderId: '278933192533',
    projectId: 'kopichat-a8dc3',
    storageBucket: 'kopichat-a8dc3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANkZCJ7YKYPIZo8UTrwctyslSpOm56Up8',
    appId: '1:278933192533:ios:b2150314d7c6aaf7c5f9dc',
    messagingSenderId: '278933192533',
    projectId: 'kopichat-a8dc3',
    storageBucket: 'kopichat-a8dc3.appspot.com',
    iosBundleId: 'com.example.kopichart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANkZCJ7YKYPIZo8UTrwctyslSpOm56Up8',
    appId: '1:278933192533:ios:b2150314d7c6aaf7c5f9dc',
    messagingSenderId: '278933192533',
    projectId: 'kopichat-a8dc3',
    storageBucket: 'kopichat-a8dc3.appspot.com',
    iosBundleId: 'com.example.kopichart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoImw5zUJ8KakACW_apfOEx69jjTHdU4E',
    appId: '1:278933192533:web:c6c648219ac3a02cc5f9dc',
    messagingSenderId: '278933192533',
    projectId: 'kopichat-a8dc3',
    authDomain: 'kopichat-a8dc3.firebaseapp.com',
    storageBucket: 'kopichat-a8dc3.appspot.com',
    measurementId: 'G-F3LQKK5EYE',
  );
}
